Fix invalid UTF-8
Current translation sync fail with:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3:
ordinal not in range(128)

Example:
http://logs.openstack.org/periodic/zun-ui-propose-translation-update/2f95b23/

The problem are two wrong " " UTF-8 characters, replace them with ASCII
ones.

Note that the diff will not show this as real difference. But comparing files before and
after using "file" shows before: UTF-8 Unicode text
And now: ASCII text.

This was introduced with change I2eba1ac77deec797342fc1adff60f45e8ea0a70f.

See
http://status.openstack.org/openstack-health/#/job/zun-ui-upstream-translation-update
for when the failures start.

Change-Id: Idd443c3a432c78374f6d10d48f759ff5787e439c